### ISSUE TITLE
二维码还没有扫就已经过期问题

### ISSUE THREAD

**Issue by anwerteq** [kebenxiaoming/matrix#1]
![image](https://github.com/kebenxiaoming/matrix/assets/45233561/c0315041-9d49-4898-acb0-7310bc834fd8)

**Comment by kebenxiaoming** [comment]
过期了没事，你点击刷新就行，是关闭了headless了吧，这个过期时间是抖音自己设置的，我们控制不了

**Comment by anwerteq** [comment]
好的，感谢
