### ISSUE TITLE
小程序扫码登录后，会重复跳出登录界面

### ISSUE THREAD

**Issue by diudiu62** [kebenxiaoming/matrix#13]
如题，不知道怎么解决了。
是否有交流群，互相帮助下吧。

**Comment by kebenxiaoming** [comment]
可以描述下具体问题，上传到的是哪个平台等，最好贴出报错代码，目前没有群哈

**Comment by diudiu62** [comment]
没事了，是stealth.min.js的路径错了，导致chromium一直登陆
