### ISSUE TITLE
小红书登陆异常

### ISSUE THREAD

**Issue by diudiu62** [kebenxiaoming/matrix#14]
![image](https://github.com/user-attachments/assets/25b4a10f-0479-48d7-a360-d5393fbfbbe1)
如代码，我在core中的request加了打印。
出现chromium界面后，我点击二维码，扫码后，接口返回失败。

**Comment by diudiu62** [comment]
作者可以加微信吗？wx：cype62

**Comment by diudiu62** [comment]
自己又排查出了问题，是xhs依赖不能用最新的，用pip install xhs 安装就可以。
作者方便也可以加微信，关于产品化，有空可以聊一聊

**Comment by kebenxiaoming** [comment]
小红书参考这个项目：https://github.com/ReaJason/xhs
有问题可以查阅该项目文档，先加个好友，有问题私下沟通吧
