### ISSUE TITLE
为什么要使用playwright 执行前要先加载 这个 js 呢？ 

### ISSUE THREAD

**Issue by BluerAngala** [kebenxiaoming/matrix#16]
![PixPin_2024-12-16_11-23-52](https://github.com/user-attachments/assets/5cfab03e-d9dd-42d6-bcb0-260295a6150e)

**Comment by kebenxiaoming** [comment]
这个问题请查阅https://github.com/ReaJason/xhs这个项目哈，他的文档里有说明，如果有其他疑问可以在该项目中咨询作者
