### ISSUE TITLE
关于mysql的小白问题

### ISSUE THREAD

**Issue by JXXXX001** [kebenxiaoming/matrix#6]
大佬，我安装了mysql以及将matrix.sql导入mysql，在执行user_queue_login.py的mycursor.execute("SELECT id,uid,type FROM mx_account_login_queue WHERE status=0 AND type="f"{type}")  查询语句时，mycursor.fetchall()始终是空的，求问大佬如何解决，万分感谢！
![image](https://github.com/kebenxiaoming/matrix/assets/75160463/94a9cf90-8376-484a-a683-498786433f82)

**Comment by kebenxiaoming** [comment]
status改为0就可以了，SELECT id,uid,type FROM mx_account_login_queue WHERE status=0 AND type="f"{type}，这条SQL有两个条件，一个是status为0，一个是type（登陆类型）
