### ISSUE TITLE
希望增加海外自媒体

### ISSUE THREAD

**Issue by AnakinCN** [kebenxiaoming/matrix#7]
另外，如何联系作者您本人？微信？

**Comment by kebenxiaoming** [comment]
这个项目用的是playwright，海外的项目只要是有网页端也一样可以接入

**Comment by AnakinCN** [comment]
方便的话把微信通过邮件发给我吧：  21st_anakin   哀特  sina。com

**Comment by kebenxiaoming** [comment]
我的微信：bGFwdWRhMjAxNA==

**Comment by AnakinCN** [comment]
搜不到啊，bGFwdWRhMjAxNA==  ？ 是这个吗？
----- 原始邮件 -----
发件人：sunnier ***@***.***>
收件人：kebenxiaoming/matrix ***@***.***>
抄送人：AnakinCN ***@***.***>,  Author ***@***.***>
主题：Re:_[kebenxiaoming/matrix]_希望增加海外自媒体_(Issue_#7)
日期：2024年08月15日 15点09分


我的微信：bGFwdWRhMjAxNA==
